import { StyleSheet } from "react-native";
import theme from "./theme";
const colors = theme.colors;

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.bg },
  screen: { flex: 1, backgroundColor: colors.bg },
  center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.bg },
  content: { flex: 1 },
  contentInner: { padding: 18, paddingBottom: 118 },
  authBg: { flex: 1, backgroundColor: "#0b1f33" },
  authOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "transparent" },
  authPanel: { margin: 0, paddingHorizontal: 24, paddingTop: 32, paddingBottom: 40, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: "#fffaf1", gap: 14 },
  authTitle: { fontSize: 28, fontWeight: "800", color: "#0b1f33", letterSpacing: -0.5 },
  authCopy: { color: "#475569", lineHeight: 22, fontSize: 14 },
  authLogo: { alignItems: "center", justifyContent: "center", paddingTop: 60, paddingBottom: 28 },
  authLogoMark: { width: 56, height: 56, borderRadius: 16, backgroundColor: "#fffaf1", alignItems: "center", justifyContent: "center", marginBottom: 14 },
  authLogoTitle: { fontSize: 22, fontWeight: "800", color: "#fffaf1", letterSpacing: -0.3 },
  authLogoSub: { fontSize: 13, color: "rgba(255,250,241,0.6)", marginTop: 4 },
  authDivider: { height: 1, backgroundColor: "#ded8cc", marginVertical: 4 },
  authInputLabel: { fontSize: 12, fontWeight: "700", color: "#475569", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: -6 },
  fieldError: { color: "#a43131", fontSize: 12, fontWeight: "600", marginTop: -6 },
  fieldSuccess: { color: "#16a34a", fontSize: 12, fontWeight: "600", marginTop: -6 },
  passwordHint: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: -4 },
  passwordHintText: { fontSize: 12, color: "#64748b" },
  passwordHintMet: { fontSize: 12, color: "#16a34a", fontWeight: "600" },
  pendingIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: "#e8f7ef", alignItems: "center", justifyContent: "center", marginBottom: 12 },
  passwordToggle: { position: "absolute", right: 12, top: 13, padding: 4 },
  inputWrap: { position: "relative" },
  header: { marginBottom: 16 },
  eyebrow: { color: colors.green, fontSize: 12, fontWeight: "800", textTransform: "uppercase" },
  title: { fontSize: 27, fontWeight: "800", color: colors.ink, marginTop: 4 },
  muted: { color: colors.muted, lineHeight: 21 },
  metaText: { color: colors.muted, fontSize: 12, fontWeight: "700" },
  label: { color: colors.ink, fontWeight: "800", marginTop: 2 },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 13,
    backgroundColor: colors.surface,
    color: colors.ink
  },
  textArea: { minHeight: 86, paddingTop: 12, textAlignVertical: "top" },
  panel: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 15,
    gap: 12,
    marginBottom: 14
  },
  primaryButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.green,
    borderRadius: 8,
    paddingHorizontal: 14,
    marginTop: 4
  },
  secondaryButton: {
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.blue,
    backgroundColor: "#eef2f6",
    borderRadius: 8,
    paddingHorizontal: 14
  },
  ghostButton: {
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.surface
  },
  smallButton: {
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.blue,
    borderRadius: 8,
    paddingHorizontal: 12,
    marginTop: 10,
    alignSelf: "flex-start"
  },
  dangerButton: {
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingHorizontal: 12
  },
  dangerButtonWide: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingHorizontal: 14
  },
  primaryButtonText: { color: "#ffffff", fontWeight: "800" },
  secondaryButtonText: { color: colors.blue, fontWeight: "800" },
  link: { color: colors.blue, fontWeight: "800", textAlign: "center", paddingVertical: 8 },
  error: { color: colors.red, backgroundColor: "#fff1f2", padding: 10, borderRadius: 8, marginBottom: 12 },
  success: { color: colors.green, backgroundColor: "#e8f7ef", padding: 10, borderRadius: 8, marginBottom: 12 },
  pending: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, gap: 14 },
  statsRow: { flexDirection: "row", gap: 10, marginBottom: 16 },
  statBox: { flex: 1, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, padding: 13 },
  statValue: { color: colors.ink, fontSize: 26, fontWeight: "800" },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 4 },
  sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: "800", marginTop: 12, marginBottom: 10 },
  toolCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, overflow: "hidden", marginBottom: 12 },
  toolImage: { width: "100%", height: 150, backgroundColor: "#e2e8f0" },
  toolBody: { padding: 13, gap: 7 },
  cardTitle: { color: colors.ink, fontWeight: "800", fontSize: 16 },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  actionRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8, flexWrap: "wrap" },
  badge: {
    alignSelf: "flex-start",
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: colors.chip,
    color: colors.ink,
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: "capitalize"
  },
  points: { color: colors.gold, fontWeight: "800" },
  badgeMuted: { backgroundColor: "#eceff3", color: colors.muted },
  listItem: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, padding: 14, marginBottom: 10, gap: 6 },
  modalShade: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(31,41,51,0.34)" },
  modalPanel: { backgroundColor: colors.surface, padding: 18, borderTopLeftRadius: 8, borderTopRightRadius: 8, gap: 12, maxHeight: "90%" },
  modalPanelTall: { backgroundColor: colors.surface, padding: 18, borderTopLeftRadius: 8, borderTopRightRadius: 8, gap: 12, maxHeight: "92%" },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7 },
  chipActive: { borderWidth: 1, borderColor: colors.green, backgroundColor: "#e8f7ef", borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7, color: colors.green, overflow: "hidden" },
  chipText: { color: colors.muted, fontWeight: "800", fontSize: 12 },
  chipTextActive: { color: colors.green },
  toggleRow: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surface
  },
  feedCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, overflow: "hidden", marginBottom: 12 },
  feedImage: { width: "100%", height: 170, backgroundColor: "#e2e8f0" },
  previewImage: { width: "100%", height: 170, borderRadius: 8, backgroundColor: "#e2e8f0" },
  feedBody: { padding: 13, gap: 7 },
  postPromptCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 9
  },
  promptAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center"
  },
  promptAvatarText: { color: "#ffffff", fontWeight: "800" },
  promptInput: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 999,
    backgroundColor: "#fbfaf7",
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 7
  },
  promptText: { color: colors.muted, fontWeight: "700" },
  promptIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fbfaf7"
  },
  feedSortRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
  feedSortChip: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    gap: 6
  },
  feedSortActive: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.green,
    flexDirection: "row",
    alignItems: "center",
    gap: 6
  },
  feedSortText: { color: colors.green, fontWeight: "800", fontSize: 12 },
  feedSortActiveText: { color: "#ffffff", fontWeight: "800", fontSize: 12 },
  redditPostCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    marginBottom: 12,
    flexDirection: "row",
    overflow: "hidden"
  },
  voteRail: {
    width: 44,
    backgroundColor: "#fbfaf7",
    borderRightWidth: 1,
    borderColor: colors.line,
    alignItems: "center",
    paddingTop: 13,
    gap: 4
  },
  voteText: { color: colors.ink, fontWeight: "800", fontSize: 12 },
  postContent: { flex: 1, padding: 13, gap: 8 },
  postMetaRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 7 },
  communityBadge: {
    color: colors.green,
    backgroundColor: colors.chip,
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: "800"
  },
  postActions: { flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap", paddingTop: 2 },
  postAction: {
    minHeight: 32,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "#fbfaf7",
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    alignItems: "center",
    gap: 5
  },
  profileCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12
  },
  avatar: { width: 74, height: 74, borderRadius: 37, backgroundColor: "#e2e8f0" },
  avatarSmall: { width: 52, height: 52, borderRadius: 26, backgroundColor: "#e2e8f0", borderWidth: 3, borderColor: colors.surface },
  avatarFloat: { position: "absolute", top: 124, left: 16, zIndex: 2 },
  profileInfo: { flex: 1, gap: 5 },
  filterHeader: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  chatBox: { borderWidth: 1, borderColor: colors.line, borderRadius: 8, padding: 10, gap: 8, maxHeight: 280 },
  chatBubble: { backgroundColor: "#f8fafc", borderRadius: 8, padding: 10, gap: 3 },
  tabbar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 78,
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderColor: colors.line,
    paddingTop: 8
  },
  tabItem: { flex: 1, alignItems: "center", gap: 3, paddingHorizontal: 1 },
  tabTextActive: { color: colors.green }
  ,
  smallBadge: { position: "absolute", right: -8, top: -8, backgroundColor: colors.red, borderRadius: 12, width: 24, height: 24, alignItems: "center", justifyContent: "center" },
  primaryButtonDisabled: { opacity: 0.5, backgroundColor: colors.muted },
  linkRow: { flexDirection: "row", justifyContent: "center", alignItems: "center", paddingVertical: 8 }
});
