import { StyleSheet } from "react-native";
import theme from "./theme";
const colors = theme.colors;

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.bg },
  screen: { flex: 1, backgroundColor: colors.bg },
  center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.bg },
  content: { flex: 1 },
  contentInner: { padding: 18, paddingBottom: 118 },
  authBg: { flex: 1 },
  authOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(31,41,51,0.34)" },
  authPanel: { margin: 18, padding: 22, borderRadius: 8, backgroundColor: "rgba(255,255,255,0.97)", gap: 12 },
  authTitle: { fontSize: 31, fontWeight: "800", color: colors.ink },
  authCopy: { color: colors.muted, lineHeight: 21 },
  header: { marginBottom: 16 },
  eyebrow: { color: colors.green, fontSize: 12, fontWeight: "800", textTransform: "uppercase" },
  title: { fontSize: 27, fontWeight: "800", color: colors.ink, marginTop: 4 },
  muted: { color: colors.muted, lineHeight: 21 },
  metaText: { color: colors.muted, fontSize: 12, fontWeight: "700" },
  label: { color: colors.ink, fontWeight: "800", marginTop: 2 },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 13,
    backgroundColor: colors.surface,
    color: colors.ink
  },
  textArea: { minHeight: 86, paddingTop: 12, textAlignVertical: "top" },
  panel: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 15,
    gap: 12,
    marginBottom: 14
  },
  primaryButton: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.green,
    borderRadius: 8,
    paddingHorizontal: 14,
    marginTop: 4
  },
  secondaryButton: {
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.blue,
    backgroundColor: "#eef6ff",
    borderRadius: 8,
    paddingHorizontal: 14
  },
  ghostButton: {
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.surface
  },
  smallButton: {
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.blue,
    borderRadius: 8,
    paddingHorizontal: 12,
    marginTop: 10,
    alignSelf: "flex-start"
  },
  dangerButton: {
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingHorizontal: 12
  },
  dangerButtonWide: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.red,
    borderRadius: 8,
    paddingHorizontal: 14
  },
  primaryButtonText: { color: "#ffffff", fontWeight: "800" },
  secondaryButtonText: { color: colors.blue, fontWeight: "800" },
  link: { color: colors.blue, fontWeight: "800", textAlign: "center", paddingVertical: 8 },
  error: { color: colors.red, backgroundColor: "#fff1f2", padding: 10, borderRadius: 8, marginBottom: 12 },
  success: { color: colors.green, backgroundColor: "#e8f7ef", padding: 10, borderRadius: 8, marginBottom: 12 },
  pending: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, gap: 14 },
  statsRow: { flexDirection: "row", gap: 10, marginBottom: 16 },
  statBox: { flex: 1, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, padding: 13 },
  statValue: { color: colors.ink, fontSize: 26, fontWeight: "800" },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 4 },
  sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: "800", marginTop: 12, marginBottom: 10 },
  toolCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, overflow: "hidden", marginBottom: 12 },
  toolImage: { width: "100%", height: 150, backgroundColor: "#e2e8f0" },
  toolBody: { padding: 13, gap: 7 },
  cardTitle: { color: colors.ink, fontWeight: "800", fontSize: 16 },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  actionRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8, flexWrap: "wrap" },
  badge: {
    alignSelf: "flex-start",
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: colors.chip,
    color: colors.ink,
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: "capitalize"
  },
  points: { color: colors.gold, fontWeight: "800" },
  listItem: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, padding: 14, marginBottom: 10, gap: 6 },
  modalShade: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(31,41,51,0.34)" },
  modalPanel: { backgroundColor: colors.surface, padding: 18, borderTopLeftRadius: 8, borderTopRightRadius: 8, gap: 12, maxHeight: "90%" },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7 },
  chipActive: { borderWidth: 1, borderColor: colors.green, backgroundColor: "#e8f7ef", borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7, color: colors.green, overflow: "hidden" },
  chipText: { color: colors.muted, fontWeight: "800", fontSize: 12 },
  chipTextActive: { color: colors.green },
  toggleRow: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surface
  },
  feedCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, overflow: "hidden", marginBottom: 12 },
  feedImage: { width: "100%", height: 170, backgroundColor: "#e2e8f0" },
  previewImage: { width: "100%", height: 170, borderRadius: 8, backgroundColor: "#e2e8f0" },
  feedBody: { padding: 13, gap: 7 },
  profileCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12
  },
  avatar: { width: 74, height: 74, borderRadius: 37, backgroundColor: "#e2e8f0" },
  profileInfo: { flex: 1, gap: 5 },
  chatBox: { borderWidth: 1, borderColor: colors.line, borderRadius: 8, padding: 10, gap: 8, maxHeight: 280 },
  chatBubble: { backgroundColor: "#f8fafc", borderRadius: 8, padding: 10, gap: 3 },
  tabbar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 78,
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderColor: colors.line,
    paddingTop: 8
  },
  tabItem: { flex: 1, alignItems: "center", gap: 3, paddingHorizontal: 1 },
  tabText: { color: colors.muted, fontSize: 10, fontWeight: "800" },
  tabTextActive: { color: colors.green }
  ,
  smallBadge: { position: "absolute", right: -8, top: -8, backgroundColor: colors.red, borderRadius: 12, width: 24, height: 24, alignItems: "center", justifyContent: "center" }
});
